### ISSUE TITLE
Drop .metricSource. nesting level

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#145]
PR #111 added DataSource to the spec, which increased the flexibility.

But I think the implementation ended up more verbose than it could've. This is the level of nesting for a simple ratioMetric: `spec.indicator.spec.ratioMetric.good.metricSource.spec.query`.

I'm not sure what purpose the `.metricSource.` serves in there. I wonder if we couldn't drop it. Instead define `thresholdMetric` and ratioMetric's `good`, `bad` and `ugly` as being "of type metricSource", so the nesting would drop by at least one level to: `spec.indicator.spec.ratioMetric.good.spec.query`.

(We could leave defining it with `.metricSource.` included for backwards compatibility.)

**Comment by proffalken** [comment]
IIRC, the `metricSource` was meant to be something like `datadog` or `prometheus`, so you end up with `spec.indicator.spec.ratioMetric.good.DATADOG.spec.query`.

This was so that we could have provider specific queries executed to get the `ratioMetric` back without worrying about building that into the spec itself, so you could use PromQL, DDQL, Splunk, LogQL, or any other string as the query text.

**Comment by mmazur** [comment]
Ah, right, now it rings a bell (it's not immediately obvious from scanning the spec that that's how this works). Though I'm still slightly confused by how to define this precisely.

Anyway, I have a use case where this syntax isn't optimal – the metric source is implied from the environment (e.g. all SLOs are for the exact same source; or the file name/directory structure enforces the metric source) and therefore an explicit definition in the source serves no purpose.

Please leave this issue up. I'll get back to it when I have time and modify it to make a case for a change.

**Comment by mmazur** [comment]
Superseded by #160, closing
