### ISSUE TITLE
CRD API group should be a domain name

### ISSUE THREAD

**Issue by Hy3n4** [OpenSLO/OpenSLO#234]
### Problem to solve

In the schema definition and all examples, there is `apiVersion: openslo/v1` used and I believe it should be `apiVersion: openslo.com/v1`.

### Proposal

Change the CRD group to `openslo.com` in the schema to be compliant with Kubernetes standards.

As a result, the definition should be usable like this in the manifest:
```
apiVersion: openslo.com/v1
Kind: SLO
...
```

### Further details

For now, it's causing troubles in real-life implementations. Furthermore, the `apiextension-server` has a validation for it. So the definition in the current state violates the rules.

### Links / references
[apiextension validation rule](https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/validation/validation.go#L296)

**Comment by nieomylnieja** [comment]
hey @Hy3n4, thanks for opening up this issue :)

While there is a mention in OpenSLO goals of _"Compliance with the Kubernetes YAML format"_, I'm not quiet convinced this should imply OpenSLO direct compliance with k8s CRD spec.
OpenSLO is a specification in of itself, not directly tied to any vendor or tool, thus I don't see a strong reason that It should be changed, especially since this is a breaking change, OpenSLO is already utilised by different tools/vendors which expect the `apiVersion` in the current format.

There is already an issue open which aims at providing a solution to the problem you've described: https://github.com/OpenSLO/OpenSLO/issues/87. If we'd be to provide such CRD's within this project, we could easily do the translation from OpenSLO spec to CRD with [oslo](https://github.com/OpenSLO/oslo).

**Comment by fourstepper** [comment]
Hi, with all due respect, it's not understandable to me how it's possible to have "Compliance with the Kubernetes YAML format" written under "Goals" of the spec as the first point and then completely failing to meet this goal in the first line of any spec definition (the `apiVersion`). 

In my opinion, there are three ways forward here:

1. Remove this goal from the list of goals, if it's not met and no change/action is planned 
2. Fix it in the `v1` of the spec and break the different tools' and vendors' workflows 
3. Fix it in `v2` of the spec

If I want to build a Kubernetes-based product on top of the specification today, it's impossible to do in compliance with what's written in the README of https://github.com/OpenSLO/OpenSLO .

**Comment by nieomylnieja** [comment]
I see, I wasn't fully aware CRDs format was fully synonymous with _Kubernetes YAML format_. I also was not around back when these decisions for goals and `apiVersion` were set in stone. I think the only viable option is to introduce `v2alpha` asap and correct the `apiVersion` constraints there, wdyt?

**Comment by nieomylnieja** [comment]
This document lists the proposals for `v2`: https://github.com/OpenSLO/OpenSLO/blob/main/enhancements/v2alpha1.md#datasource, If you're willing please open a PR with your proposal and the changes listed in this document :)

**Comment by fourstepper** [comment]
Yeah, that sounds good. I will work on the PR during this week @nieomylnieja
