### ISSUE TITLE
Define target between 0-100

### ISSUE THREAD

**Issue by metalmatze** [OpenSLO/OpenSLO#26]
During my past work on [slo-libsonnet](https://github.com/metalmatze/slo-libsonnet/) I had several people point out that writing targets between `0-1` by hand seems weird and not intuitive. 
Especially targets like `99.5` are a lot more readable than `0.995`. Given that OpenSLO is also meant to by written by hand I wanted to bring it up here, as it's been brought up with me before.

It's somewhat related to #24 but still different enough to have a separate issue, I believe.

**Comment by mmazur** [comment]
This is unfortunately settled in the spec and it's indeed a bit weird.

Fix would be either of:
1. add: `targetPercent` or
2. interpret `target` as percent if value >1. 

Though the second option is probably too weird.

**Comment by proffalken** [comment]
Keep in mind that whilst v 1.0.0 of the spec has been published, the spec is there to be moulded, challenged, and shaped by comments exactly like this.

I suspect this issue was missed by some of us (I certainly didn't see it!), but it definitely makes sense that some way of helping people write "human-readable" percentages rather than "computer accurate" percentages should be incorporated at a future date.

**Comment by programmer04** [comment]
Related a little bit duplicated issues https://github.com/OpenSLO/OpenSLO/issues/24 & https://github.com/OpenSLO/OpenSLO/issues/137 (comment added for visibility)

**Comment by mmazur** [comment]
With #155 getting merged, this is now resolved, closing.
