### ISSUE TITLE
Use `valid` instead of `total`

### ISSUE THREAD

**Issue by alexewerlof** [OpenSLO/OpenSLO#262]
Reading [v2alpha1](https://github.com/OpenSLO/OpenSLO/blob/main/enhancements/v2alpha1.md) spec I see the `total` is still there from v1.

Maybe it's a nit, but I suggest using `valid` instead for reasons that I've explained [here](https://blog.alexewerlof.com/p/valid-vs-total).

Essentially, the formula for SLI is:

`good / valid x 100`

The distinction between `valid` and `total` enables the users to see the possibility to scope their optimization effort to what they see in their area of responsibility and control as well as preventing false alerts for things that are clearly not.

**Comment by nieomylnieja** [comment]
Hey @alexewerlof, thanks for bringing this up :) (and the other issue)
We're planning next community meeting between 3th and 7th of June (18:00 UTC).
You can either let me know here which day(s) suit you best or vote directly on our Slack, there's an invite link at the bottom of https://openslo.com/

**Comment by alexewerlof** [comment]
We discussed this today and decided not to change the standard because:

1. It's too late. This small change has massive ramifications to implementation
2. "Total" seems to be the convention in other tools as well
3. Although "valid" is used in the SRE books, _total_ is easier to understand

**Comment by fourstepper** [comment]
I think this is not to be closed just yet - [discussion is ongoing on Slack](https://openslo.slack.com/archives/C0202J83M3R/p1728506960437269)

**Comment by fpiwowarczyk** [comment]
> I think this is not to be closed just yet - [discussion is ongoing on Slack](https://openslo.slack.com/archives/C0202J83M3R/p1728506960437269)

I'll move my thoughts in here, slack is nasty and blures old messages in free version. 

During the community meeting we I have been pro changing the name to `valid` instead of `total`. I will rephrase my arguments to have all arguments on board, but after sleeping with this idea I have changed my mind a bit. I think this discussion is important, because our current arguments doesn't solve the case, at some point we may come back to the idea of changing the name again. 

My argumentation was that we serve as guideline, we guarantee that using our spec will be the correct way of describing SLOs as code. Because of that I think we should use the best naming as possible. 

As my previous argument is still valid, I think we should keep the name `total`. Arguments provided in @alexewerlof article, are interesting but probably should be solved by picking different SLI or actually be reflected in SLO. SLI should be metric that reflects how users see your system. It doesn't mean that you didn't have control over an incident, because your vendor had an incident, if your users couldn't use your system, they don't really care. 

I hope that @alexewerlof will not feel offended that I will use his arguments to describe my point. I think article is great, it describes the problem in a way that it is easy to understand, is relatable and most importantly it serves as great starting point for discussion!

[Here](https://blog.alexewerlof.com/p/valid-vs-total) I'm citing article mentioned before in Issue. 

1. Correctly, chosen SLI should be total requests made by `users` of the system. We can see in here there was a problem with picking correct SLI. But this are still `total` requests that users have made.  
```
Example: request latency

❌ Latency of all requests to our backend (API, static, etc.)

✔️ Latency of API calls excluding the health check
``` 
 
2. I'm not sure whether both of this are correct SLIs. `High priority` can be really subjective term and SLO can be actually misleading, probably I'd focus on Availability in here.
```
Another example: incident resolution time

❌ Time to resolve an incident

✔️ Time to resolve high priority incidents
```

3. Website uptime is actually great SLI. Users do not care about your vendors, if they are failing it should be reflected on your SLO. If you are below your objectives, probably you should consider changing them, move to highly available solution etc. 
```
Another example: website uptime

❌ Website uptime

✔️ Uptime minus the cloud provider downtime minus outage due to maintenance planned windows
```

4. When your API fails it fails, show it on SLO. I think this is the same situation as described in previous point. Do something w with it, most of the time you are able to focus on it.
```
❌ User facing API success rate (our API may fail due to our dependencies)

✔️ User facing API success rate for errors that are not due to failure in our dependencies or content that the team doesn’t control
```

5. Nature of DDoS is that it is hard to differentiate from actual users that are not malicious. Show it on SLO. If you have too many attacks, SLO should tell you that it is time for investing into attack mitigation solutions. 
```
❌ All API calls

✔️ Authenticated API calls (we don’t want to be punished for DDoS attacks or any other unintended usage of the API surface)
```

It was said few times already picking correct SLI is the hardest part of creating SLO. I think this shows it the best, SLI should in simple, but in the same time show how users see your system,  it isn't simple thing to do. Suggesting users to use `valid` events only suggest that they should sometime `cut` part of them because we couldn't do anything about it, this is really subjective thing and it can lead to the situation when users don't want to use your system because it isn't reliable, but all your SLOs are about their threshold. 

Sorry for requesting to reopen this issue to actually propose keeping things the same :D and big thanks to Alex for bringing this discussion!

**Comment by fourstepper** [comment]
Reading the examples, I am actually even more in favor of `total` than before.

The reason is that `total` always represents the actual total of whatever you are trying to measure, and it doesn't matter if that includes or doesn't include a DDoS attack - that's up to you. `valid` in this case IS actually "scoping" what the user could consider more than `total`, IMO

For example, in the case of website uptime, I also disagree. You should design your system INCLUDING your cloud provider downtime/SLA, because you can't actually provider higher results than the infrastructure that you depend on provides. And the developers implementing SLOs for their services should be acutely aware of this fact. 

Same as `✔️ User facing API success rate for errors that are not due to failure in our dependencies or content that the team doesn’t control` - this just honestly makes no sense? User doesn't care if his error is because of you or your dependency - he got an error and that's it. If you wanna monitor purely what your service is doing, you should create another SLO for that.

**Comment by fpiwowarczyk** [comment]
You're right @fourstepper. Maybe it wasn't phrased good enough but I wanted to say that I have changed my mind after thinking about it bit more and we should stick to `total`,  I just expanded the reasoning beyond reasons said before. Sorry for all confusion, I'll close Issue now 🙏

**Comment by fourstepper** [comment]
It's all good, I'm glad we got to discuss this :)
